// export const data = []

export const data = [
  {
    title: 'BOTH SEXES',
    frenchTitle: 'HOMMES ET.FEMMES',
    xValue: 100,
    yValue: 15,
    xFValue: 100,
    yFValue: 35,
    jobTypeAgri: 'AGRICULTURE MINING AND FISHING',
    jobPixelsAgri: 234,
    jobColorAgri: 'red',
    jobTypeProf: 'PROFESSORS',
    jobPixelsProf: 6,
    jobColorProf: 'darkBlue',
    jobTypeDomestic: 'DOMESTIC AND PERSONAL SERVICE',
    jobPixelsDomestic: 127,
    jobColorDomestic: 'yellow',
    jobTypeCommerce: 'COMMERCE AND TRANSPORTATION',
    jobPixelsCommerce: 22,
    jobColorCommerce: 'brown',
    jobTypeMech: 'MANUFACTURING AND MECHANICAL INDUSTRIES',
    jobPixelsMech: 22,
    jobColorMech: 'green',
  },
  {
    title: 'MALES',
    frenchTitle: 'HOMMES',
    xValue: 300,
    yValue: 15,
    xFValue: 300,
    yFValue: 35,
    jobTypeAgri: 'AGRICULTURE MINING AND FISHING',
    jobPixelsAgri: 260,
    jobColorAgri: 'red',
    jobTypeProf: 'PROFESSORS',
    jobPixelsProf: 3,
    jobColorProf: 'darkBlue',
    jobTypeDomestic: 'DOMESTIC AND PERSONAL SERVICE',
    jobPixelsDomestic: 88,
    jobColorDomestic: 'yellow',
    jobTypeCommerce: 'COMMERCE AND TRANSPORTATION',
    jobPixelsCommerce: 30,
    jobColorCommerce: 'brown',
    jobTypeMech: 'MANUFACTURING AND MECHANICAL INDUSTRIES',
    jobPixelsMech: 30,
    jobColorMech: 'green',
  },
  {
    title: 'FEMALES',
    frenchTitle: 'FEMMES',
    xValue: 480,
    yValue: 15,
    xFValue: 480,
    yFValue: 35,
    jobTypeAgri: 'AGRICULTURE PECHE ET.MINES',
    jobPixelsAgri: 182,
    jobColorAgri: 'red',
    jobTypeProf: 'PROFESSORS',
    jobPixelsProf: 2,
    jobColorProf: 'darkBlue',
    jobTypeDomestic: 'SERVIDE DOMESTIQUE ET PERSONNEL',
    jobPixelsDomestic: 212,
    jobColorDomestic: 'yellow',
    jobTypeCommerce: 'COMMERCE ET TRANSPORT',
    jobPixelsCommerce: 2,
    jobColorCommerce: 'brown',
    jobTypeMech: 'INDUSTRIES AND MANUFACTURIERES ET MECANIQUES',
    jobPixelsMech: 13,
    jobColorMech: 'green',
  },
];
